# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='taskstatus_id',
            field=models.IntegerField(verbose_name='\u72b6\u6001id'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='taskstatus_name',
            field=models.CharField(default='', help_text='\u72b6\u6001\u540d\u79f0', max_length=30, verbose_name='\u72b6\u6001\u540d\u79f0'),
        ),
    ]
